ssr
campari229/Memcrab-tt pull request #1
Opened 2020-11-04 08:25 UTC by campari229

SSR

2020-11-04 08:53 UTC, max-mykhailenko requested changes

2020-11-04 08:53 UTC, max-mykhailenko commented on package.json
> +    "sass": "^1.28.0"
Всегда зависимости прописывай четкие. Чтобы не дописывать каждый раз --exact при установке пакета создай файл .npmrc и внеси эту настройку туда

2020-11-04 08:53 UTC, max-mykhailenko commented on src/client/index.jsx
> +delete window.__PRELOADED_STATE__
Это что-то тебе даст?

2020-11-04 08:53 UTC, max-mykhailenko commented on src/client/lib/lib.js
> +  for (let i = 0; i < columns; i++) {
перепиши цикл функционально без использования for

2020-11-04 08:53 UTC, max-mykhailenko commented on src/client/lib/lib.js
> +  for (let i = 0; i < rows; i++) {
перепиши цикл функционально без использования for

2020-11-04 08:53 UTC, max-mykhailenko commented on src/client/lib/lib.js
> +    for (let i = 0; i < array[0].length; i++) {
перепиши цикл функционально без использования for

2020-11-04 08:53 UTC, max-mykhailenko commented on src/server.js
> +            '\\u003c'
скажи в каких целях здесь этот код

2020-11-04 08:53 UTC, max-mykhailenko commented on src/server.js
> +  const params = req.path.match(/(?<=)\d+/gi)
Опиши работу этой регулярки

2020-11-04 09:06 UTC, campari229 commented on src/client/index.jsx
> +delete window.__PRELOADED_STATE__
По сути ничего, убрал.

2020-11-04 09:17 UTC, campari229 commented on src/server.js
> +            '\\u003c'
JSON.stringify(state) для того что бы передать стор из сервера на клиент, а replace тут не нужен)

2020-11-04 09:18 UTC, campari229 commented on src/server.js
> +  const params = req.path.match(/(?<=)\d+/gi)
она матчит числа после знака =

2020-11-04 13:29 UTC, max-mykhailenko commented on src/client/index.jsx
> +delete window.__PRELOADED_STATE__
Почему думаешь что ничего? :)

2020-11-04 13:29 UTC, max-mykhailenko commented on src/server.js
> +            '\\u003c'
Почему не нужен? А зачем его вообще пишут?

2020-11-06 13:21 UTC, max-mykhailenko requested changes

2020-11-06 13:21 UTC, max-mykhailenko commented on package.json
> +    "babel-core": "^7.0.0-bridge.0",
Зачем использовать bridge.0 ?

2020-11-06 13:21 UTC, max-mykhailenko commented on package.json
> +    "express": "^4.14.0",
зависимости по прежнему не четкие

2020-11-06 13:21 UTC, max-mykhailenko commented on src/client/index.jsx
> +// delete window.__PRELOADED_STATE__
Проверь влияние этого удаление на память через chrome devtools memory

2020-11-06 13:21 UTC, max-mykhailenko commented on src/client/lib/lib.js
> +let id = 1;
нельзя использовать константы во внешней области видимости

2020-11-06 13:21 UTC, max-mykhailenko commented on src/client/lib/lib.js
> +  const arr = new Array(columns).fill("#");
"#" зачем заполнять глупостями

2020-11-06 13:21 UTC, max-mykhailenko commented on src/client/lib/lib.js
> +  const arr = new Array(rows).fill("#");
"#" зачем заполнять глупостями, есть https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from куда можно передать функцию обработки, а количество элементов задать через первый аргумент {length: X}

2020-11-06 13:21 UTC, max-mykhailenko commented on src/client/lib/lib.js
> +      row.forEach((cell, index) => {
forEach та ну, есть reduce, который хорошо справляется с такого рода суммами

2020-11-06 13:21 UTC, max-mykhailenko commented on src/client/lib/lib.js
> +          id: id++
мутирование во внешнюю область видимости. При ssr повлияет на других пользователей

2020-11-06 13:21 UTC, max-mykhailenko commented on src/client/lib/lib.js
> +  arr.filter(item => item.id !== target.id)
результаты работы функции фильтрации никуда не записываются, а значит это нерабочая строка

2020-11-06 13:21 UTC, max-mykhailenko commented on src/client/lib/lib.js
> +    return [...arr].splice(0, numberOfClosest)
используй slice

2020-11-06 14:19 UTC, campari229 commented on src/client/index.jsx
> +// delete window.__PRELOADED_STATE__
Ого, что то я не ожидал такого, теперь все ясно...

2020-11-09 09:12 UTC, max-mykhailenko requested changes

2020-11-09 09:12 UTC, max-mykhailenko commented on src/client/lib/lib.js
> +    const res = Array.from(tempoArr, () => {
Array.from(tempoArr — это и так массив, зачем с него делать массив? я же писал что есть конструкция Array.from({length: X}, () => {})

2020-11-09 09:12 UTC, max-mykhailenko commented on src/client/lib/lib.js
> +      index++;
внешний эффект, напиши без него

2020-11-09 09:12 UTC, max-mykhailenko commented on src/client/lib/lib.js
> +  let arr = array.flat()
почему let?

2020-11-09 09:12 UTC, max-mykhailenko commented on src/client/lib/lib.js
> +    return arr.slice(targetIndex - gap, targetIndex + gap).filter(item => item.id !== target.id)
.filter(item => item.id !== target.id) повторяется со строчки в строчку, вынеси повыше

2020-11-09 11:45 UTC, campari229 commented on src/client/lib/lib.js
> +    const res = Array.from(tempoArr, () => {
Я переписал на Array.from но по пока непонятным мне причинам этот код не попал в коммит, постараюсь проверять коммиты внимательней.

2020-11-09 12:50 UTC, max-mykhailenko approved these changes

2020-11-09 12:57 UTC, merged